site_name: Watkins Mill Computer Science
# site_url: https://drjmarino.github.io/website/
nav:
    - index.md
    - Awesome Class:
        - awesome/awesome01.md
        - awesome/awesome02.md
        - awesome/awesome03.md  
        - awesome/awesome04.md  
        - awesome/awesome05.md  
        - awesome/awesome06.md  
        - awesome/awesome07.md  
        - awesome/awesome08.md   
        - awesome/awesome09.md  
        - awesome/awesome10.md   
        - awesome/awesome11.md
        - awesome/awesome12.md
        - awesome/awesome13.md  
        - awesome/awesome14.md  
        - awesome/awesome15.md  
        - awesome/awesome16.md  
        - awesome/awesome17.md  
        - awesome/awesome18.md   
        - awesome/awesome19.md  
        - awesome/awesome20.md     
        - awesome/awesome21.md
        - awesome/awesome22.md
        - awesome/awesome23.md  
        - awesome/awesome24.md  
        - awesome/awesome25.md  
        - awesome/awesome26.md        
    - Best Class: 
        - best/human01.md
        - best/human02.md
        - best/human03.md
        - best/human04.md
        - best/human05.md
        - best/human06.md
        - best/human07.md
        - best/human08.md
        - best/human09.md
        - best/human10.md
        - best/human11.md
        - best/human12.md
        - best/human13.md
        - best/human14.md
        - best/human15.md
        - best/human16.md
        - best/human17.md
        - best/human18.md
        - best/human19.md
        - best/human20.md
        - best/human21.md
        - best/human22.md
        - best/human23.md
        - best/human24.md
        - best/human25.md
        - best/human26.md
    - Fantastic Class: 
        - fantastic/human01.md
        - fantastic/human02.md
        - fantastic/human03.md
        - fantastic/human04.md
        - fantastic/human05.md
        - fantastic/human06.md
        - fantastic/human07.md
        - fantastic/human08.md
        - fantastic/human09.md
        - fantastic/human10.md
        - fantastic/human11.md
        - fantastic/human12.md
        - fantastic/human13.md
        - fantastic/human14.md
        - fantastic/human15.md
        - fantastic/human16.md
        - fantastic/human17.md
        - fantastic/human18.md
        - fantastic/human19.md
        - fantastic/human20.md
        - fantastic/human21.md
        - fantastic/human22.md
        - fantastic/human23.md
        - fantastic/human24.md
        - fantastic/human25.md
        - fantastic/human26.md
    - Marvelous Class: 
        - marvelous/human01.md
        - marvelous/human02.md
        - marvelous/human03.md
        - marvelous/human04.md
        - marvelous/human05.md
        - marvelous/human06.md
        - marvelous/human07.md
        - marvelous/human08.md
        - marvelous/human09.md
        - marvelous/human10.md
        - marvelous/human11.md
        - marvelous/human12.md
        - marvelous/human13.md
        - marvelous/human14.md
        - marvelous/human15.md
        - marvelous/human16.md
        - marvelous/human17.md
        - marvelous/human18.md
        - marvelous/human19.md
        - marvelous/human20.md
        - marvelous/human21.md
        - marvelous/human22.md
        - marvelous/human23.md
        - marvelous/human24.md
        - marvelous/human25.md
        - marvelous/human26.md
    - Primo Class: 
        - primo/human01.md
        - primo/human02.md
        - primo/human03.md
        - primo/human04.md
        - primo/human05.md
        - primo/human06.md
        - primo/human07.md
        - primo/human08.md
        - primo/human09.md
        - primo/human10.md
        - primo/human11.md
        - primo/human12.md
        - primo/human13.md
        - primo/human14.md
        - primo/human15.md
        - primo/human16.md
        - primo/human17.md
        - primo/human18.md
        - primo/human19.md
        - primo/human20.md
        - primo/human21.md
        - primo/human22.md
        - primo/human23.md
        - primo/human24.md
        - primo/human25.md
        - primo/human26.md
    - Savvy Class: 
        - savvy/human01.md
        - savvy/human02.md
        - savvy/human03.md
        - savvy/human04.md
        - savvy/human05.md
        - savvy/human06.md
        - savvy/human07.md
        - savvy/human08.md
        - savvy/human09.md
        - savvy/human10.md
        - savvy/human11.md
        - savvy/human12.md
        - savvy/human13.md
        - savvy/human14.md
        - savvy/human15.md
        - savvy/human16.md
        - savvy/human17.md
        - savvy/human18.md
        - savvy/human19.md
        - savvy/human20.md
        - savvy/human21.md
        - savvy/human22.md
        - savvy/human23.md
        - savvy/human24.md
        - savvy/human25.md
        - savvy/human26.md


theme:
    name: material
    logo: 
    favicon: 
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    features:
        - content.tabs.link
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.path
        - content.code.copy
        - content.code.annotate
    markdown_extensions:
     - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
     - pymdownx.inlinehilite
     - pymdownx.snippets
     - pymdownx.superfences
    icon:
        repo: material/github
plugins:
    - search
